### ISSUE TITLE
Translation

### ISSUE THREAD

**Issue by Xzavier0707** [aematsubara/RealisticVillagers#19]
I have translated the language part of the config and message files, can I upload them to you? (And do you have a discord?)

**Comment by aematsubara** [comment]
Hi! Thanks for your contribution, my discord is: AEM#5693 if you got any issues!

However, multi-language isn't something I'm planning to add atm since that would require an update of messages in every update, but maybe in a future I'll create one of those pages where people can contribute with translations!

Have a nice day!
