### ISSUE TITLE
Gifts

### ISSUE THREAD

**Issue by RavanelloMarrone** [aematsubara/RealisticVillagers#20]
Villagers don't pick up gifts but only look at them. There are no errors in the console. Version 1.19.3

**Comment by aematsubara** [comment]
I need more details on this, does this happen always or only sometimes? Does the villager have available space in the inventory? In the villager's menu, in the villager's information, what is the activity he's in (it can be WORK/IDLE/MEETING/etc.)?

I thought this was already fixed in previous versions but it seems that it wasn't :/

**Comment by RavanelloMarrone** [comment]
I tried with a lot of different items, it always happen

![2023-01-05_21 28 25](https://user-images.githubusercontent.com/46332352/210874241-c63be775-cf6d-4838-a64c-11c5f8a940f1.png)
![2023-01-05_21 29 21](https://user-images.githubusercontent.com/46332352/210874246-2836b13c-017b-47ed-a050-5e020b7905e9.png)
![2023-01-05_21 28 03](https://user-images.githubusercontent.com/46332352/210874249-7698b608-399d-477e-9765-8ec1a704dc1f.png)

**Comment by aematsubara** [comment]
Make sure that the gamerule mobGriefing is true and that you have the latest ProtocolLib dev-build, if the issue still happening, please show me all the /plugins you're using, maybe other plugin is preventing the villager from picking item; I couldn't replicate this issue on my server.

**Comment by RavanelloMarrone** [comment]
I enabled mobGriefing and now it works. Thanks!

**Comment by aematsubara** [comment]
Good to know!
